from .camera_presets_node import NODE_CLASS_MAPPINGS as CAMERA_MAPPINGS
from .camera_presets_node import NODE_DISPLAY_NAME_MAPPINGS as CAMERA_DISPLAY
from .lighting_presets_node import NODE_CLASS_MAPPINGS as LIGHTING_MAPPINGS
from .lighting_presets_node import NODE_DISPLAY_NAME_MAPPINGS as LIGHTING_DISPLAY
from .sdxl_resolution_node import NODE_CLASS_MAPPINGS as RESOLUTION_MAPPINGS
from .sdxl_resolution_node import NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_DISPLAY
from .scheduler_selector_node import NODE_CLASS_MAPPINGS as SCHEDULER_MAPPINGS
from .scheduler_selector_node import NODE_DISPLAY_NAME_MAPPINGS as SCHEDULER_DISPLAY
from .sampler_selector_node import NODE_CLASS_MAPPINGS as SAMPLER_MAPPINGS
from .sampler_selector_node import NODE_DISPLAY_NAME_MAPPINGS as SAMPLER_DISPLAY

NODE_CLASS_MAPPINGS = {**CAMERA_MAPPINGS, **LIGHTING_MAPPINGS, **RESOLUTION_MAPPINGS, **SCHEDULER_MAPPINGS, **SAMPLER_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**CAMERA_DISPLAY, **LIGHTING_DISPLAY, **RESOLUTION_DISPLAY, **SCHEDULER_DISPLAY, **SAMPLER_DISPLAY}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
