from .camera_presets_node import NODE_CLASS_MAPPINGS as CAMERA_MAPPINGS
from .camera_presets_node import NODE_DISPLAY_NAME_MAPPINGS as CAMERA_DISPLAY
from .lighting_presets_node import NODE_CLASS_MAPPINGS as LIGHTING_MAPPINGS
from .lighting_presets_node import NODE_DISPLAY_NAME_MAPPINGS as LIGHTING_DISPLAY
from .sdxl_resolution_node import NODE_CLASS_MAPPINGS as RESOLUTION_MAPPINGS
from .sdxl_resolution_node import NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_DISPLAY
from .scheduler_selector_node import NODE_CLASS_MAPPINGS as SCHEDULER_MAPPINGS
from .scheduler_selector_node import NODE_DISPLAY_NAME_MAPPINGS as SCHEDULER_DISPLAY
from .sampler_selector_node import NODE_CLASS_MAPPINGS as SAMPLER_MAPPINGS
from .sampler_selector_node import NODE_DISPLAY_NAME_MAPPINGS as SAMPLER_DISPLAY
from .text_split_node import NODE_CLASS_MAPPINGS as TEXT_SPLIT_MAPPINGS
from .text_split_node import NODE_DISPLAY_NAME_MAPPINGS as TEXT_SPLIT_DISPLAY
from .list_get_index_node import NODE_CLASS_MAPPINGS as LIST_INDEX_MAPPINGS
from .list_get_index_node import NODE_DISPLAY_NAME_MAPPINGS as LIST_INDEX_DISPLAY

NODE_CLASS_MAPPINGS = {**CAMERA_MAPPINGS, **LIGHTING_MAPPINGS, **RESOLUTION_MAPPINGS, **SCHEDULER_MAPPINGS, **SAMPLER_MAPPINGS, **TEXT_SPLIT_MAPPINGS, **LIST_INDEX_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**CAMERA_DISPLAY, **LIGHTING_DISPLAY, **RESOLUTION_DISPLAY, **SCHEDULER_DISPLAY, **SAMPLER_DISPLAY, **TEXT_SPLIT_DISPLAY, **LIST_INDEX_DISPLAY}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
